"use strict";

const bcrypt = require("bcrypt");

/** @type {import('sequelize-cli').Migration} */
module.exports = {
  async up(queryInterface, Sequelize) {
    const items = [
      {
        firstName: "Hendrick",
        lastName: "Fayer",
        userName: "hfayer0",
        password: "dN5&Ez|%t(`!",
        bio: "Nullam sit amet turpis elementum ligula vehicula consequat. Morbi a ipsum. Integer a nibh.\n\nIn quis justo. Maecenas rhoncus aliquam lacus. Morbi quis tortor id nulla ultrices aliquet.\n\nMaecenas leo odio, condimentum id, luctus nec, molestie sed, justo. Pellentesque viverra pede ac diam. Cras pellentesque volutpat dui.",
        email: "hfayer0@spotify.com",
        imagePath: "http://dummyimage.com/161x100.png/cc0000/ffffff",
      },
      {
        firstName: "Brennen",
        lastName: "Munt",
        userName: "bmunt1",
        password: "sY2<@jTV",
        bio: "Mauris enim leo, rhoncus sed, vestibulum sit amet, cursus id, turpis. Integer aliquet, massa id lobortis convallis, tortor risus dapibus augue, vel accumsan tellus nisi eu orci. Mauris lacinia sapien quis libero.",
        email: "bmunt1@vistaprint.com",
        imagePath: "http://dummyimage.com/107x100.png/cc0000/ffffff",
      },
      {
        firstName: "Darline",
        lastName: "Proudlock",
        userName: "dproudlock2",
        password: "gC6$#`Py(\\Z7",
        bio: "Phasellus sit amet erat. Nulla tempus. Vivamus in felis eu sapien cursus vestibulum.",
        email: "dproudlock2@altervista.org",
        imagePath: "http://dummyimage.com/196x100.png/dddddd/000000",
      },
      {
        firstName: "Glynn",
        lastName: "Band",
        userName: "gband3",
        password: "kJ0~HipGKlL,C5xA",
        bio: "Integer tincidunt ante vel ipsum. Praesent blandit lacinia erat. Vestibulum sed magna at nunc commodo placerat.\n\nPraesent blandit. Nam nulla. Integer pede justo, lacinia eget, tincidunt eget, tempus vel, pede.\n\nMorbi porttitor lorem id ligula. Suspendisse ornare consequat lectus. In est risus, auctor sed, tristique in, tempus sit amet, sem.",
        email: "gband3@answers.com",
        imagePath: "http://dummyimage.com/225x100.png/dddddd/000000",
      },
      {
        firstName: "Doroteya",
        lastName: "Iacobucci",
        userName: "diacobucci4",
        password: "vL8?Gn0'{b.%d#",
        bio: "Nullam porttitor lacus at turpis. Donec posuere metus vitae ipsum. Aliquam non mauris.",
        email: "diacobucci4@mozilla.org",
        imagePath: "http://dummyimage.com/219x100.png/dddddd/000000",
      },
      {
        firstName: "Ichabod",
        lastName: "Crispin",
        userName: "icrispin5",
        password: "gO3+c|%o#e\\7",
        bio: "Duis consequat dui nec nisi volutpat eleifend. Donec ut dolor. Morbi vel lectus in quam fringilla rhoncus.\n\nMauris enim leo, rhoncus sed, vestibulum sit amet, cursus id, turpis. Integer aliquet, massa id lobortis convallis, tortor risus dapibus augue, vel accumsan tellus nisi eu orci. Mauris lacinia sapien quis libero.",
        email: "icrispin5@wix.com",
        imagePath: "http://dummyimage.com/241x100.png/cc0000/ffffff",
      },
      {
        firstName: "Gustavo",
        lastName: "Cornelissen",
        userName: "gcornelissen6",
        password: "dA9,s=O2|l`cEK)*",
        bio: "In sagittis dui vel nisl. Duis ac nibh. Fusce lacus purus, aliquet at, feugiat non, pretium quis, lectus.\n\nSuspendisse potenti. In eleifend quam a odio. In hac habitasse platea dictumst.",
        email: "gcornelissen6@gravatar.com",
        imagePath: "http://dummyimage.com/112x100.png/5fa2dd/ffffff",
      },
      {
        firstName: "Kristofer",
        lastName: "Shiels",
        userName: "kshiels7",
        password: "wQ9|d5qIuT+Os\\",
        bio: "Integer tincidunt ante vel ipsum. Praesent blandit lacinia erat. Vestibulum sed magna at nunc commodo placerat.\n\nPraesent blandit. Nam nulla. Integer pede justo, lacinia eget, tincidunt eget, tempus vel, pede.\n\nMorbi porttitor lorem id ligula. Suspendisse ornare consequat lectus. In est risus, auctor sed, tristique in, tempus sit amet, sem.",
        email: "kshiels7@w3.org",
        imagePath: "http://dummyimage.com/165x100.png/dddddd/000000",
      },
      {
        firstName: "Morgen",
        lastName: "Pullman",
        userName: "mpullman8",
        password: "kC7`9=j?q\\rOix3",
        bio: "Morbi porttitor lorem id ligula. Suspendisse ornare consequat lectus. In est risus, auctor sed, tristique in, tempus sit amet, sem.\n\nFusce consequat. Nulla nisl. Nunc nisl.",
        email: "mpullman8@typepad.com",
        imagePath: "http://dummyimage.com/220x100.png/ff4444/ffffff",
      },
      {
        firstName: "Constanta",
        lastName: "Barme",
        userName: "cbarme9",
        password: "kF1\\K?D5sQ",
        bio: "Proin eu mi. Nulla ac enim. In tempor, turpis nec euismod scelerisque, quam turpis adipiscing lorem, vitae mattis nibh ligula nec sem.\n\nDuis aliquam convallis nunc. Proin at turpis a pede posuere nonummy. Integer non velit.",
        email: "cbarme9@imdb.com",
        imagePath: "http://dummyimage.com/116x100.png/cc0000/ffffff",
      },
      {
        firstName: "Fielding",
        lastName: "de Quincey",
        userName: "fdequinceya",
        password: "cZ4~+\\Ryc8d*qz4",
        bio: "Suspendisse potenti. In eleifend quam a odio. In hac habitasse platea dictumst.",
        email: "fdequinceya@uiuc.edu",
        imagePath: "http://dummyimage.com/174x100.png/cc0000/ffffff",
      },
      {
        firstName: "Hannis",
        lastName: "Cayford",
        userName: "hcayfordb",
        password: "uS0*dH@7",
        bio: "Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Proin risus. Praesent lectus.",
        email: "hcayfordb@canalblog.com",
        imagePath: "http://dummyimage.com/198x100.png/5fa2dd/ffffff",
      },
      {
        firstName: "Salmon",
        lastName: "Brecknall",
        userName: "sbrecknallc",
        password: "oT4{+x'TL)6q$1Q",
        bio: "Integer ac leo. Pellentesque ultrices mattis odio. Donec vitae nisi.\n\nNam ultrices, libero non mattis pulvinar, nulla pede ullamcorper augue, a suscipit nulla elit ac nulla. Sed vel enim sit amet nunc viverra dapibus. Nulla suscipit ligula in lacus.",
        email: "sbrecknallc@soundcloud.com",
        imagePath: "http://dummyimage.com/151x100.png/dddddd/000000",
      },
      {
        firstName: "Rivkah",
        lastName: "Ashford",
        userName: "rashfordd",
        password: "zU3_=2=9*URb>",
        bio: "In hac habitasse platea dictumst. Etiam faucibus cursus urna. Ut tellus.\n\nNulla ut erat id mauris vulputate elementum. Nullam varius. Nulla facilisi.",
        email: "rashfordd@kickstarter.com",
        imagePath: "http://dummyimage.com/220x100.png/dddddd/000000",
      },
      {
        firstName: "Auberta",
        lastName: "Powter",
        userName: "apowtere",
        password: "zP0@.9Srho|aX",
        bio: "Phasellus sit amet erat. Nulla tempus. Vivamus in felis eu sapien cursus vestibulum.\n\nProin eu mi. Nulla ac enim. In tempor, turpis nec euismod scelerisque, quam turpis adipiscing lorem, vitae mattis nibh ligula nec sem.",
        email: "apowtere@edublogs.org",
        imagePath: "http://dummyimage.com/185x100.png/5fa2dd/ffffff",
      },
      {
        firstName: "Lorelei",
        lastName: "Bolesworth",
        userName: "lbolesworthf",
        password: "lT7`n/@=!N",
        bio: "Quisque porta volutpat erat. Quisque erat eros, viverra eget, congue eget, semper rutrum, nulla. Nunc purus.\n\nPhasellus in felis. Donec semper sapien a libero. Nam dui.",
        email: "lbolesworthf@163.com",
        imagePath: "http://dummyimage.com/202x100.png/ff4444/ffffff",
      },
      {
        firstName: "Lindi",
        lastName: "Upjohn",
        userName: "lupjohng",
        password: "sN8~p)bfF1)",
        bio: "Nulla ut erat id mauris vulputate elementum. Nullam varius. Nulla facilisi.",
        email: "lupjohng@google.es",
        imagePath: "http://dummyimage.com/179x100.png/5fa2dd/ffffff",
      },
      {
        firstName: "Arney",
        lastName: "McIlhatton",
        userName: "amcilhattonh",
        password: "yP0,MWwX",
        bio: "In congue. Etiam justo. Etiam pretium iaculis justo.\n\nIn hac habitasse platea dictumst. Etiam faucibus cursus urna. Ut tellus.\n\nNulla ut erat id mauris vulputate elementum. Nullam varius. Nulla facilisi.",
        email: "amcilhattonh@examiner.com",
        imagePath: "http://dummyimage.com/212x100.png/dddddd/000000",
      },
      {
        firstName: "Roseanna",
        lastName: "Benthall",
        userName: "rbenthalli",
        password: "oL3*8rF#QS",
        bio: "Nullam porttitor lacus at turpis. Donec posuere metus vitae ipsum. Aliquam non mauris.\n\nMorbi non lectus. Aliquam sit amet diam in magna bibendum imperdiet. Nullam orci pede, venenatis non, sodales sed, tincidunt eu, felis.",
        email: "rbenthalli@home.pl",
        imagePath: "http://dummyimage.com/206x100.png/5fa2dd/ffffff",
      },
      {
        firstName: "Floria",
        lastName: "Simko",
        userName: "fsimkoj",
        password: "wB6!A0B>$2G\\",
        bio: "Praesent blandit. Nam nulla. Integer pede justo, lacinia eget, tincidunt eget, tempus vel, pede.",
        email: "fsimkoj@wsj.com",
        imagePath: "http://dummyimage.com/162x100.png/dddddd/000000",
      },
      {
        firstName: "Stacee",
        lastName: "Chesters",
        userName: "schestersk",
        password: "lM6&KV=ZO38",
        bio: "Praesent blandit. Nam nulla. Integer pede justo, lacinia eget, tincidunt eget, tempus vel, pede.",
        email: "schestersk@nhs.uk",
        imagePath: "http://dummyimage.com/159x100.png/cc0000/ffffff",
      },
      {
        firstName: "Bryce",
        lastName: "Sterricks",
        userName: "bsterricksl",
        password: 'qH7}&.X}"T',
        bio: "Aenean fermentum. Donec ut mauris eget massa tempor convallis. Nulla neque libero, convallis eget, eleifend luctus, ultricies eu, nibh.\n\nQuisque id justo sit amet sapien dignissim vestibulum. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Nulla dapibus dolor vel est. Donec odio justo, sollicitudin ut, suscipit a, feugiat et, eros.",
        email: "bsterricksl@tripod.com",
        imagePath: "http://dummyimage.com/133x100.png/cc0000/ffffff",
      },
      {
        firstName: "Adler",
        lastName: "Oller",
        userName: "aollerm",
        password: "sC1{Jo<kst'Pv",
        bio: "Curabitur in libero ut massa volutpat convallis. Morbi odio odio, elementum eu, interdum eu, tincidunt in, leo. Maecenas pulvinar lobortis est.",
        email: "aollerm@bigcartel.com",
        imagePath: "http://dummyimage.com/246x100.png/ff4444/ffffff",
      },
      {
        firstName: "Sayre",
        lastName: "Casemore",
        userName: "scasemoren",
        password: "yK7$eB%.3G",
        bio: "Cras non velit nec nisi vulputate nonummy. Maecenas tincidunt lacus at velit. Vivamus vel nulla eget eros elementum pellentesque.\n\nQuisque porta volutpat erat. Quisque erat eros, viverra eget, congue eget, semper rutrum, nulla. Nunc purus.\n\nPhasellus in felis. Donec semper sapien a libero. Nam dui.",
        email: "scasemoren@google.ru",
        imagePath: "http://dummyimage.com/229x100.png/cc0000/ffffff",
      },
      {
        firstName: "Vanny",
        lastName: "Witcher",
        userName: "vwitchero",
        password: "bD4>21Aj0hy1>",
        bio: "Sed sagittis. Nam congue, risus semper porta volutpat, quam pede lobortis ligula, sit amet eleifend pede libero quis orci. Nullam molestie nibh in lectus.\n\nPellentesque at nulla. Suspendisse potenti. Cras in purus eu magna vulputate luctus.",
        email: "vwitchero@privacy.gov.au",
        imagePath: "http://dummyimage.com/105x100.png/dddddd/000000",
      },
    ];
    items.forEach((item) => {
      item.password = bcrypt.hashSync(item.password, 10); // Hashing password
      item.createdAt = Sequelize.literal("NOW()");
      item.updatedAt = Sequelize.literal("NOW()");
    });
    await queryInterface.bulkInsert("Users", items, {});
  },

  async down(queryInterface, Sequelize) {
    await queryInterface.bulkDelete("Users", null, {});
  },
};
